### ISSUE TITLE
Support for permafrost

### ISSUE THREAD

**Issue by VorTechnix** [dayer4b/dirtcraft#1]
Your mod looks good but it would be even better is it supported crafting of permafrost with moss and permafrost with rocks. If you want I could make the addition myself.

**Comment by dayer4b** [comment]
that's a good idea!  I'll try to do that this weekend.  But if you want to make a PR, feel free to fork and give it a shot.

thanks!

**Comment by dayer4b** [comment]
release v0.2.0 should satisfy this

**Comment by VorTechnix** [comment]
Thanks! You have 1 new subscriber!
