### ISSUE TITLE
Dry Dirt handeling

### ISSUE THREAD

**Issue by VorTechnix** [dayer4b/dirtcraft#4]
![image](https://user-images.githubusercontent.com/45538536/136819785-f5eb91e9-ccd6-4172-bfdc-951d86e1f368.png)
For some reason dirtcraft misses `dry_dirt` variants when creating recipes. I plan to rewrite the fuzzy logic on my fork to fix this. If you want I can make a pull request when I'm done.

Also `dry_dirt` + `water_bucket` should make regular dirt and regular dirt should be smelt-able into `dry_dirt`. (I'll add this in my fork as well).

**Comment by VorTechnix** [comment]
It turns out the problem was caused by the gsub regex on [https://github.com/dayer4b/dirtcraft/blob/22adec3d8db49e44a11a2701c32aee65c881ae79/init.lua#L71](init.lua#L71). I'll make a pull request with the fix.

The pull request will also have the dirt/dry_dirt conversion recipes.

**Comment by dayer4b** [comment]
thanks for the work!  This issue is closed by the merging of #5
